{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DADOS_ATIVIDADE\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DADOS_ATIVIDADE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b871b103-9f36-47da-a14d-1206d1734f54",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71033b43-2077-4ba9-98f8-460fe2ff6191",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f71e4c9-e4e9-4617-b42b-4a2855f5a76c",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3fd1289-7f7d-4131-b6e0-f65cdce7f373",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e4f910c-4190-4688-8710-e73edc355619",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4f9c581-9068-4071-a298-204aefde1c59",
            "sourceColumn": "Column6",
            "summarizeBy": "none"
          },
          {
            "name": "Column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97c4e251-9a54-43ac-9dce-101ccb58269e",
            "sourceColumn": "Column7",
            "summarizeBy": "none"
          },
          {
            "name": "Column8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7666eec-caf4-4b33-a892-9508a81b572b",
            "sourceColumn": "Column8",
            "summarizeBy": "none"
          },
          {
            "name": "Column9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a05c09f0-09cc-4d73-afbd-417f95c6f55d",
            "sourceColumn": "Column9",
            "summarizeBy": "none"
          },
          {
            "name": "Column10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d62a6365-ede8-4238-97af-45c2ee9d6865",
            "sourceColumn": "Column10",
            "summarizeBy": "none"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76360180-7615-486d-aa3a-bfba9d6ae76b",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c64458ee-896c-48e1-8c5c-4ad8eb35124e",
            "sourceColumn": "Column12",
            "summarizeBy": "none"
          },
          {
            "name": "Column13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0934e1a-dd5e-4954-9962-dba39d703012",
            "sourceColumn": "Column13",
            "summarizeBy": "none"
          },
          {
            "name": "Column14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93b05814-0c92-4b57-af31-5663c7dda34d",
            "sourceColumn": "Column14",
            "summarizeBy": "none"
          },
          {
            "name": "Column15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35dfc056-ed22-49da-9c1a-4a6f1dd9dd6c",
            "sourceColumn": "Column15",
            "summarizeBy": "none"
          },
          {
            "name": "Column16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "441a2bbf-85fc-46d3-b8b3-5b32c421376d",
            "sourceColumn": "Column16",
            "summarizeBy": "none"
          },
          {
            "name": "Column17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76dfc2f0-237d-4f35-bb1d-3e3e9db14fd8",
            "sourceColumn": "Column17",
            "summarizeBy": "none"
          },
          {
            "name": "Column18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ecba78e-bd2e-4b5a-a5a5-5f9452461a0f",
            "sourceColumn": "Column18",
            "summarizeBy": "none"
          },
          {
            "name": "Column19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17e97c35-2fbd-4ea4-bb6b-e9456af667d0",
            "sourceColumn": "Column19",
            "summarizeBy": "none"
          },
          {
            "name": "Column20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5fdaafd-be11-4b81-8fc2-f2e83dc46f49",
            "sourceColumn": "Column20",
            "summarizeBy": "none"
          },
          {
            "name": "Column21",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74cc57a8-045f-45ec-a965-b88a5b2a13ad",
            "sourceColumn": "Column21",
            "summarizeBy": "none"
          },
          {
            "name": "Column22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc96a33-057a-4f91-97b8-b43ccb577b00",
            "sourceColumn": "Column22",
            "summarizeBy": "none"
          },
          {
            "name": "Column23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad797964-e920-4df6-b3be-d487b1777fff",
            "sourceColumn": "Column23",
            "summarizeBy": "none"
          },
          {
            "name": "Column24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eed6ce9a-cd9f-4413-aa38-90d287eb4a3c",
            "sourceColumn": "Column24",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dbbf18fd-8ea7-41de-b493-d8fd257fe178",
        "partitions": [
          {
            "name": "DADOS_ATIVIDADE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\luis.hl\\Downloads\\DADOS_ATIVIDADE.csv\"),[Delimiter=\",\", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_61f23f44-9497-4356-9d5e-10fbc0d9b694",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "54178ee1-c115-41bc-8714-94e489315b05",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4438dd1a-b548-4298-a0e0-26f95655fe8c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0be45786-7b5d-49b0-a704-1aed8e43071e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dd718d5d-29f3-48c4-8835-5b6273295eda",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b8477058-25f9-4b1e-a23a-22fe201c308f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "24308cf6-fcef-490c-963c-296bf6e87c77",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b4b67891-109f-4b2b-8c29-f138f3e5a54e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6494febc-0a39-4dd0-bb13-c45da4165ceb",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "dfb9b457-b490-4aa7-bc5a-a7cd812e050c",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "2374280e-9726-4e53-906c-e006738156cf",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "6900236b-bd40-4782-9b20-af09882fbf4c",
                "ordinal": 3
              }
            ],
            "lineageTag": "81c7d1ae-7711-4710-b1af-b17ecfbe3de6"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3cfc37b2-2c2f-4f97-8dcd-7159ab95e5e9",
        "partitions": [
          {
            "name": "DateTableTemplate_61f23f44-9497-4356-9d5e-10fbc0d9b694",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}